### ISSUE TITLE
About the datas in the example

### ISSUE THREAD

**Issue by chzeze** [XuezheMax/NeuroNLP2#2]
Hi Max,
could you share the datas which is used in the example ?
such as the datas in the path :  data/conll2003/english/ or data/POS-penn/wsj/split1/ 
thanks.

**Comment by XuezheMax** [comment]
Hi,
I am sorry that due to the data licence, I cannot share the data publicly.
But I can show examples of the data to illustrate the format of the data files.

Part-of-speech tagging and dependency parsing data follows the CoNLL-X format:

1	The	_	DT	DT	_	2	NMOD
2	company	_	NN	NN	_	3	SUB
3	had	_	VB	VBD	_	0	ROOT
4	sought	_	VB	VBN	_	3	VC
5	increases	_	NN	NNS	_	4	OBJ
6	totaling	_	VB	VBG	_	5	NMOD
7	$	_	$	$	_	13	P
8	80.3	_	CD	CD	_	7	AMOD
9	million	_	CD	CD	_	7	AMOD
10	,	_	,	,	_	13	P
11	or	_	CC	CC	_	13	NMOD
12	22	_	CD	CD	_	13	NMOD
13	%	_	NN	NN	_	6	OBJ
14	.	_	.	.	_	3	P

1	The	_	DT	DT	_	2	NMOD
2	decision	_	NN	NN	_	3	SUB
3	was	_	VB	VBD	_	0	ROOT
4	announced	_	VB	VBN	_	3	VC
5	after	_	IN	IN	_	4	VMOD
6	trading	_	NN	NN	_	7	SUB
7	ended	_	VB	VBD	_	5	SBAR
8	.	_	.	.	_	3	P

The NER data examples are in the following:

1 CRICKET NNP I-NP O
2 - : O O
3 LEICESTERSHIRE NNP I-NP B-ORG
4 TAKE NNP I-NP O
5 OVER IN I-PP O
6 AT NNP I-NP O
7 TOP NNP I-NP O
8 AFTER NNP I-NP O
9 INNINGS NNP I-NP O
10 VICTORY NN I-NP O
11 . . O O

1 By IN I-PP O
2 stumps NNS I-NP O
3 Kent NNP B-NP B-ORG
4 had VBD I-VP O
5 reached VBN I-VP O
6 108 CD I-NP O
7 for IN I-PP O
8 three CD I-NP O
9 . . O O

**Comment by chzeze** [comment]
thank you very much
